# Generated by Django 2.1 on 2018-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=30)),
                ('candidate_party', models.CharField(max_length=30)),
                ('candidate_age', models.CharField(max_length=30)),
                ('candidate_description', models.CharField(max_length=500)),
            ],
        ),
    ]
