# Generated by Django 3.0.2 on 2021-12-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('election_name', models.CharField(max_length=50)),
                ('election_region', models.CharField(default='', max_length=50)),
                ('election_date', models.DateField(null=True)),
                ('candidate_count', models.IntegerField(default=0)),
                ('election_description', models.TextField(default='', max_length=500)),
                ('election_pic', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=30)),
                ('candidate_party', models.CharField(max_length=30)),
                ('candidate_age', models.CharField(max_length=30)),
                ('candidate_description', models.CharField(max_length=500)),
                ('candidate_pic', models.FileField(upload_to='')),
                ('candidate_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
            ],
        ),
    ]
