# Generated by Django 2.1 on 2018-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_candidate_election_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='election',
            name='election_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='election',
            name='election_region',
            field=models.CharField(default='', max_length=50),
        ),
    ]
