# Generated by Django 2.1 on 2018-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20180930_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
