# Generated by Django 2.1 on 2018-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20180930_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election_id',
        ),
        migrations.RemoveField(
            model_name='election',
            name='election_id',
        ),
        migrations.AddField(
            model_name='election',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
