# Generated by Django 2.1 on 2018-09-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20180930_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='election.Election'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='election_id',
            field=models.CharField(default=0, max_length=16, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
