# Generated by Django 2.1 on 2018-09-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20180930_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election_id',
        ),
    ]
