# Generated by Django 2.1 on 2018-10-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_remove_candidate_election_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='election.Election'),
            preserve_default=False,
        ),
    ]
