# Generated by Django 2.1 on 2018-10-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_candidate_election_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_pic',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
