# Generated by Django 2.1 on 2018-10-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_candidate_candidate_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='election_id',
            new_name='candidate_election',
        ),
    ]
