# Generated by Django 2.1 on 2018-10-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20181004_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
