# Generated by Django 2.0.5 on 2018-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterId', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=10)),
                ('candidateHash', models.CharField(max_length=256)),
            ],
        ),
    ]
