# Generated by Django 2.0.5 on 2018-10-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('previousHash', models.CharField(max_length=256)),
                ('nonce', models.IntegerField(default=0)),
                ('hash', models.CharField(max_length=256)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Transaction')),
            ],
        ),
    ]
