# Generated by Django 2.1 on 2018-10-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_auto_20180929_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=50)),
                ('candidate_hash', models.CharField(max_length=100)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ActiveVoter')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Transaction'),
        ),
    ]
