# Generated by Django 2.1 on 2018-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='candidate_hash',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='salt',
            field=models.CharField(default='f609bb5266', max_length=100),
        ),
    ]
