# Generated by Django 2.1 on 2018-10-11 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='voter',
        ),
        migrations.AddField(
            model_name='transaction',
            name='voter_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
