# Generated by Django 2.1 on 2018-10-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='transaction',
        ),
        migrations.AddField(
            model_name='block',
            name='transaction_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
