# Generated by Django 2.1 on 2018-10-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20181013_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
