# Generated by Django 2.1 on 2018-10-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_delete_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.BooleanField(default=False)),
            ],
        ),
    ]
