# Generated by Django 2.1 on 2018-08-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveVoters',
            new_name='ActiveVoter',
        ),
    ]
