# Generated by Django 2.1 on 2018-08-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180830_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activevoter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AlterField(
            model_name='activevoter',
            name='voter_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='adhaar_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
