# Generated by Django 2.1 on 2018-08-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180830_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='activevoter',
            name='has_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='age',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='voter',
            name='profile_image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
