# Generated by Django 2.1 on 2018-09-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='ec_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
