# Generated by Django 2.1 on 2018-09-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180907_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
